name: EusRemoteDesktop
version: ${project.version}
main: cc.eumc.eusremotedesktop.EusRemoteDesktop
api-version: 1.17
depend: [ EusMapDisplay ]
authors: [ EucalyptusLeaves ]
website: www.eumc.cc
commands:
  remotedesktop:
permissions:
  remotedesktop.use:
    description: Permission for accessing remote desktop