name: EusScreenMirroring
version: ${project.version}
main: cc.eumc.screenmirroring.EusScreenMirroring
api-version: 1.17
depend: [ EusMapDisplay ]
authors: [ EucalyptusLeaves ]
website: www.eumc.cc
commands:
  screenmirroring:
permissions:
  screenmirroring.use:
    description: Permission for accessing screen mirroring